export enum ResponseMessageCode {
  DISCOVERY_ANNOUNCEMENT = 200,
  DEVICE_FUNCTION_ASSIGNED = 201,
  SENSOR_CONFIGURATION_ACKNOWLEDGEMENT = 202,
  NETWORK_CONFIGURATION_ACKNOWLEDGEMENT = 203,
  FIRMWARE_UPDATE_STATUS = 204,
  REBOOT_CONFIRMATION = 205,
  DIAGNOSTIC = 206,
  OFFLINE_COMMAND_QUEUE_STATUS = 207,
  STATUS = 208,
  HEARTBEAT = 209,
  HARDWARE_METRICS = 210,
  TELEMETRY_DATA = 211,
}
