version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: iot_mongodb
    ports:
      - "50000:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      # create the default database name (matches DB_URI in your .env)
      MONGO_INITDB_DATABASE: auth
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
